import * as APIUtil from '../util/chatroom_api_util';

export const RECEIVE_NEW_MESSAGE = "RECEIVE_NEW_MESSAGE";
export const RECEIVE_UPDATED_MESSAGE = "RECEIVE_UPDATED_MESSAGE";
export const RECEIVE_CHATROOM_MESSAGES = "RECEIVE_CHATROOM_MESSAGES";
export const RECEIVE_NON_USER_CHATROOMS = "RECEIVE_NON_USER_CHATROOMS";
export const RECEIVE_USER_CHATROOMS = "RECEIVE_USER_CHATROOMS";
export const RECEIVE_CHATROOM = "RECEIVE_CHATROOM";
